Document: xlxecho
Title: Debian xlxecho Manual
Author: <insert document author here>
Abstract: This manual describes what xlxecho is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xlxecho/xlxecho.sgml.gz

Format: postscript
Files: /usr/share/doc/xlxecho/xlxecho.ps.gz

Format: text
Files: /usr/share/doc/xlxecho/xlxecho.text.gz

Format: HTML
Index: /usr/share/doc/xlxecho/html/index.html
Files: /usr/share/doc/xlxecho/html/*.html
